// For Drools Here..
package org.ufm.drools.rules

import org.ufm.drools.XMLBasedVO
import org.slf4j.Logger;

global Logger logger;

rule "Basic Transaction Transforming Rule"
    // no-loop
    when
        $vo: XMLBasedVO(transaction.system in ("Default")
            ,$version : transaction.version)
    then
        logger.debug("XMLBasedVO Rule");
        
        if ($version == null && "".equals($version))
            $vo.getTransaction().getEntity().setV("None");    
            
        // NOTE: calling Singleton class - $vo...set(Singleton.getInstance().getValue($parameters...));
    end
